[package]
name = "liber-tauri"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "liber_tauri"
path = "src/lib.rs"

[dependencies]
liber-core = { path = "../liber-core" }
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tauri.workspace = true
tauri-plugin-opener.workspace = true

[build-dependencies]
tauri-build.workspace = true

[[bin]]
name = "liber-tauri"
path = "src/main.rs"
